### ISSUE TITLE
Login as AutoZoner

### ISSUE THREAD

**Issue by yichenfeng** [yichenfeng/AAFApplicationAngular#11]
As Autozoner  
I can log in with my ignition ID and password 
So I can have my profile pulled down when I'm ready to submit my application 

- [ ] Deploy the Open AM page

**Comment by yichenfeng** [comment]
Follow up, does EVERY AutoZoner have an ignition account and password? If confirmed, then we are good.

**Comment by ryanturner** [comment]
The way we'll implement login according to @firewallkevin will remove the "login" and "logout" link.
