### ISSUE TITLE
Applicant info page 

### ISSUE THREAD

**Issue by yichenfeng** [yichenfeng/AAFApplicationAngular#16]
As the AAF team 
I want to capture the applicant information 
So that I know for whom the fund is for, and his/her status 

Acceptance Criteria
The all fields on this page are all required. If any field is empty, the applicant will not be able to submit the application (or go on to the next page??) 
<img width="1252" alt="applicant info page" src="https://cloud.githubusercontent.com/assets/24488647/21907965/7ac2c74e-d8d7-11e6-96cc-80d24e9c548e.png">

- [x] Modify layout to use Bobby's design 
- [x] Remove the previous button
- [x] Add a save for later button to allow user to exit the application 
- [x] Build in interaction with data provider service 
- [x] Validate that all fields are populated
- [x] Change the check boxes to radio button
- [x] State dropdown: 50 states +  PR + Washington D.C. (Hard code)
- [x] Change the label store number to Store Number / Department ID 
- [x] Add a question for user: are you filling this application out on behalf of someone?

**Comment by ryanturner** [comment]
Switch inputs to radio buttons

**Comment by ryanturner** [comment]
Page data should be auto-populated using the user's employee ID

**Comment by yichenfeng** [comment]
validate fields are populated

**Comment by yichenfeng** [comment]
have the UI be reviewed by bobby

**Comment by katherinetucker** [comment]
update store number to store number/department number

**Comment by katherinetucker** [comment]
Are we requiring Address 2 and Middle Name?

**Comment by katherinetucker** [comment]
talked with yichen -> requiring all but address 2
