### ISSUE TITLE
Review and Submission page - signature & submission

### ISSUE THREAD

**Issue by yichenfeng** [yichenfeng/AAFApplicationAngular#24]
As AAF 
I want the applicant to read the agreement, print his/her name, date it and sign the application 
so that I can hold them accountable legally 

One page, at the bottom of the review

**Comment by ryangraves37** [comment]
https://github.com/szimek/signature_pad

Solution cjlyth found to digitally sign the forms.

**Comment by yichenfeng** [comment]
#22

**Comment by yichenfeng** [comment]
completed & merged
