### ISSUE TITLE
How to authenticate users?

### ISSUE THREAD

**Issue by ryanturner** [yichenfeng/AAFApplicationAngular#7]
Hey all,

There's seems to be a good bit of uncertainty among the group about how we're going to handle authentication for this. During the hackathon, an ldap server was created, and the initial implementation used that. There was discussion of using an OAuth login using OpenAM.

For the sake of getting an MVP out the door, we need to make a decision. I believe that OAuth will prove to be the simpler solution that also provides the most appropriate featureset. I don't want to force that direction though -- what are your thoughts?

- [ ] documentation

**Comment by ryanturner** [comment]
@firewallkevin

**Comment by ryanturner** [comment]
@firewallkevin in today's meeting said that he'd like to use OpenAM Web Policy Agent for this. We'll need to get him to provide details on this.

**Comment by yichenfeng** [comment]
Kevin will comment on the solution @firewallkevin
